version: '3.8'

services:
  nn1:
    image: lsiksous/zoo_mini:latest
    command: "--master"
    container_name: nn1
    networks:
      zoo_network:
        ipv4_address: 172.28.1.1
  nn2:
    image: lsiksous/zoo_mini:latest
    command: "--master"
    container_name: nn2
    networks:
      zoo_network:
        ipv4_address: 172.28.1.2
  zk1:
    image: lsiksous/zoo_mini:latest
    command: "--keeper"
    container_name: zk1
    networks:
      zoo_network:
        ipv4_address: 172.28.2.1
  dn1:
    image: lsiksous/zoo_mini:latest
    command: "--slave --master-ip 172.28.1.1"
    container_name: dn1
    networks:
      zoo_network:
        ipv4_address: 172.28.3.1
  dn2:
    image: lsiksous/zoo_mini:latest
    command: "--slave --master-ip 172.28.1.1"
    container_name: dn2
    networks:
      zoo_network:
        ipv4_address: 172.28.3.2
  dn3:
    image: lsiksous/zoo_mini:latest
    command: "--slave --master-ip 172.28.1.1"
    container_name: dn3
    networks:
      zoo_network:
        ipv4_address: 172.28.3.3

networks:
  zoo_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16